name = "SignalingDimension"
uuid = "96aab1c2-4ac7-11eb-3d9a-a59b97fb3321"
authors = ["Brian Doolittle <brian.d.doolittle@gmail.com>"]
version = "0.1.0"

[deps]
BellScenario = "4e58fcc1-4405-48af-b0f2-42df636d9190"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QBase = "e52e8ede-12bf-4731-8af7-b01f6064cb11"

[compat]
julia = "1"
BellScenario = "0.1"
Combinatorics = "1.0"
QBase = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
